plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "static"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/welcome"
to = "https://menoacct-production.up.railway.app/welcome"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/login"
to = "https://menoacct-production.up.railway.app/login"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/logout"
to = "https://menoacct-production.up.railway.app/logout"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/signup"
to = "https://menoacct-production.up.railway.app/signup"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/forgot-password"
to = "https://menoacct-production.up.railway.app/forgot-password"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/reset-password/*"
to = "https://menoacct-production.up.railway.app/reset-password/:splat"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/add-email"
to = "https://menoacct-production.up.railway.app/add-email"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/invite/*"
to = "https://menoacct-production.up.railway.app/invite/:splat"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/i1"
to = "https://menoacct-production.up.railway.app/i1"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/i2"
to = "https://menoacct-production.up.railway.app/i2"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/i3"
to = "https://menoacct-production.up.railway.app/i3"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/i4"
to = "https://menoacct-production.up.railway.app/i4"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/i5"
to = "https://menoacct-production.up.railway.app/i5"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/i6"
to = "https://menoacct-production.up.railway.app/i6"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/i7"
to = "https://menoacct-production.up.railway.app/i7"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]


[[redirects]]
from = "/i8"
to = "https://menoacct-production.up.railway.app/i8"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]


[[redirects]]
from = "/i9"
to = "https://menoacct-production.up.railway.app/i9"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]


[[redirects]]
from = "/i10"
to = "https://menoacct-production.up.railway.app/i10"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]


[[redirects]]
from = "/i11"
to = "https://menoacct-production.up.railway.app/i11"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]



[[redirects]]
from = "/i12"
to = "https://menoacct-production.up.railway.app/i12"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/survey"
to = "https://menoacct-production.up.railway.app/survey"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/eliminated"
to = "https://menoacct-production.up.railway.app/eliminated"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/*"
to = "https://menoacct-production.up.railway.app/api/:splat"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/admin"
to = "https://menoacct-production.up.railway.app/admin"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/admin/*"
to = "https://menoacct-production.up.railway.app/admin/:splat"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]